trailingComma: all
tabWidth: 2
semi: true
singleQuote: true
quoteProps: 'as-needed'
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: 'always'
endOfLine: 'lf'
printWidth: 80
htmlWhitespaceSensitivity: 'css'
proseWrap: 'always'
embeddedLanguageFormatting: 'auto'
overrides:
  - files: '*.json'
    options:
      tabWidth: 2
  - files: '*.md'
    options:
      proseWrap: always
