trailingComma: es5
tabWidth: 4
semi: false
singleQuote: true
quoteProps: 'as-needed'
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: 'always'
endOfLine: 'lf'
printWidth: 100
htmlWhitespaceSensitivity: 'css'
proseWrap: 'preserve'
embeddedLanguageFormatting: 'auto'
