# Cloudinary Configuration for Jekyll
# This file contains Cloudinary-specific settings

cloudinary:
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  secure: true

  # Default transformation settings
  default_transformations:
    quality: auto
    fetch_format: auto
    dpr: auto

  # Responsive breakpoints
  responsive_breakpoints:
    - max_width: 400
      max_images: 3
    - max_width: 800
      max_images: 3
    - max_width: 1200
      max_images: 3

  # Image optimization presets
  presets:
    thumbnail:
      width: 200
      height: 200
      crop: fill
      gravity: auto
      quality: auto
      fetch_format: auto

    card:
      width: 400
      height: 300
      crop: fill
      gravity: auto
      quality: auto
      fetch_format: auto

    hero:
      width: 1200
      height: 600
      crop: fill
      gravity: auto
      quality: auto
      fetch_format: auto

    full:
      width: 1920
      quality: auto
      fetch_format: auto

  # Folder structure in Cloudinary
  folders:
    posts: 'optikalbahari/posts'
    backgrounds: 'optikalbahari/backgrounds'
    icons: 'optikalbahari/icons'
    testimonials: 'optikalbahari/testimonials'
    profile: 'optikalbahari/profile'
