name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8 # Change this to your Ruby version if needed

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install Jekyll and other gems
        run: |
          gem install jekyll jekyll-feed jekyll-paginate jekyll-sitemap jekyll-seo-tag jekyll-archives jekyll-image-size jekyll-responsive-magick

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
