name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["gh-pages"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
          cache-version: 0

      - name: Install dependencies
        run: |
          gem install bundler -v 2.2.31
          bundle install

      - name: Install Jekyll and other gems
        run: |
          gem install jekyll -v 3.9.1
          gem install jekyll-feed -v 0.15.1
          gem install jekyll-paginate -v 1.1.0
          gem install jekyll-sitemap -v 1.4.0
          gem install jekyll-seo-tag -v 2.7.1
          gem install jekyll-archives -v 2.2.1
          gem install jekyll-responsive-magick

      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages # Use the same artifact name here
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: github-pages # Ensure consistency with the uploaded artifact name
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use 'token' instead of 'github_token'
          publish_dir: ./_site # Use 'publish_dir' to specify the directory to publish
