name: Deploy Jekyll to GitHub Pages

on:
    push:
        branches:
            - master

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies (ImageMagick)
              run: sudo apt-get update && sudo apt-get install -y imagemagick

            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3.1
                  bundler-cache: true # Caches installed gems

            - name: Install Jekyll dependencies
              run: bundle install

            - name: Build Jekyll site
              run: |
                  JEKYLL_ENV=production bundle exec jekyll build
                  ls -la _site  # ✅ Debugging step to verify the build output

            - name: Verify _site directory exists
              run: test -d _site && echo "_site exists!" || (echo "_site is missing! Build failed." && exit 1)

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./_site # Ensure this path is correct

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
